from collections.abc import Iterator

import pytest
from fastapi.testclient import TestClient
from pydantic import SecretStr, ValidationError

from layerloupe.config import Settings, get_settings
from layerloupe.main import app


@pytest.fixture(autouse=True)
def _isolate_env(monkeypatch: pytest.MonkeyPatch) -> Iterator[None]:
    """Strip every env var so tests start from a clean baseline."""
    for key in list(os_environ_keys()):
        monkeypatch.delenv(key, raising=False)
    get_settings.cache_clear()
    yield
    get_settings.cache_clear()


def os_environ_keys() -> list[str]:
    import os

    return list(os.environ.keys())


def test_defaults_load_without_env() -> None:
    s = Settings()
    assert str(s.registry_url) == "https://localhost:5000/"
    assert str(s.registry_public_url) == str(s.registry_url)
    assert s.ssl_verify is True
    assert s.allow_delete is False
    assert s.allow_registry_login is False
    assert s.title == "LayerLoupe"
    assert s.cache_ttl == 30
    assert s.page_size == 100


def test_session_secret_autogenerated() -> None:
    s1 = Settings()
    s2 = Settings()
    assert isinstance(s1.session_secret, SecretStr)
    assert s1.session_secret.get_secret_value()
    # Two separate instances → two different generated secrets.
    assert s1.session_secret.get_secret_value() != s2.session_secret.get_secret_value()


def test_invalid_registry_url_raises(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("REGISTRY_URL", "not-a-url")
    with pytest.raises(ValidationError):
        Settings()


def test_public_url_defaults_to_registry_url(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("REGISTRY_URL", "https://internal:5000")
    s = Settings()
    assert str(s.registry_public_url) == str(s.registry_url)


def test_public_url_can_be_overridden(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("REGISTRY_URL", "https://internal:5000")
    monkeypatch.setenv("REGISTRY_PUBLIC_URL", "https://registry.example.com")
    s = Settings()
    # ``registry_public_url`` is a free-form string — it preserves whatever
    # the user typed (no AnyHttpUrl normalization, no trailing slash added).
    assert s.registry_public_url == "https://registry.example.com"
    assert str(s.registry_url) == "https://internal:5000/"


def test_public_url_accepts_bare_host(monkeypatch: pytest.MonkeyPatch) -> None:
    """``docker pull`` doesn't take a scheme; allow bare host:port too."""
    monkeypatch.setenv("REGISTRY_PUBLIC_URL", "registry.example.com:5000")
    s = Settings()
    assert s.registry_public_url == "registry.example.com:5000"


def test_ui_username_without_password_raises(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("UI_USERNAME", "admin")
    with pytest.raises(ValidationError):
        Settings()


def test_secret_str_does_not_leak_in_repr(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("REGISTRY_PASSWORD", "supersecret")
    s = Settings()
    assert "supersecret" not in repr(s)
    assert "supersecret" not in str(s)
    assert s.registry_password is not None
    assert s.registry_password.get_secret_value() == "supersecret"


def test_cache_ttl_validation(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("CACHE_TTL", "-1")
    with pytest.raises(ValidationError):
        Settings()


def test_page_size_bounds(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("PAGE_SIZE", "0")
    with pytest.raises(ValidationError):
        Settings()
    monkeypatch.setenv("PAGE_SIZE", "10000")
    with pytest.raises(ValidationError):
        Settings()


def test_get_settings_is_cached() -> None:
    s1 = get_settings()
    s2 = get_settings()
    assert s1 is s2  # lru_cache returns the same instance


def test_info_endpoint_uses_settings(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("REGISTRY_URL", "https://registry.example.com:443")
    monkeypatch.setenv("TITLE", "Test Registry")
    monkeypatch.setenv("ALLOW_DELETE", "true")
    get_settings.cache_clear()

    with TestClient(app) as client:
        r = client.get("/api/info")
    assert r.status_code == 200
    body = r.json()
    assert body["title"] == "Test Registry"
    assert body["allow_delete"] is True
    assert "registry.example.com" in body["registry_url"]
    assert "password" not in body
    assert "session_secret" not in body
